### ISSUE TITLE
Support PHP 8.0

### ISSUE THREAD

**Issue by HaiTo** [mercari/dietcube#36]
# Background
Dietcube doesn't work on PHP8.0. 
DietCube cannot run on PHP8.0 due to
- Twig 1.X doesn't support PHP 8.0
- PHP Unit 5.x doesn't support PHP 8.0

Also, We want to use the modern feature since PHP version 7.X and 8.X 

# Goal
1. Runnable on PHP 8.0 
2. Be more helpful for developing.

# Milestones
## V1.1
- [ ] Drop legacy PHP supports
  - 5.x
  - 7.1
  - 7.2
- [ ] Pin required PHP version at 7.3
- [ ] Upgrade dependencies. At least until the latest version that runs on 7.3
- [ ] Add type hints on PHP Doc and function arguments/returns
- [ ] [Nice to have] More documents.

## V2.0
- [ ] Be Runnable at PHP 8.0
- [ ] Address broken codes.
- [ ] Drop Supporting PHP
  - 7.3
- [ ] [Nice to have] Be property type declaration.
