### ISSUE TITLE
V1.1

### ISSUE THREAD

**Issue by HaiTo** [mercari/dietcube#37]
Original issue: https://github.com/mercari/dietcube/issues/36

# Background
Dietcube doesn't work on PHP8.0. 
DietCube cannot run on PHP8.0 due to
- Twig 1.X doesn't support PHP 8.0
- PHP Unit 5.x doesn't support PHP 8.0

Also, We want to use the modern feature since PHP version 7.X and 8.X 

# Goal
Give away too legacy PHP versions and use them as stepping minestone to upgrade to 8.0

# Milestones
## V1.1
- [ ] Drop legacy PHP supports
  - 5.x
  - 7.1
  - 7.2
- [ ] Pin required PHP version at 7.3
- [ ] Upgrade dependencies. At least until the latest version that runs on 7.3
- [ ] Add type hints on PHP Doc and function arguments/returns
- [ ] [Nice to have] More documents.

**Comment by DQNEO** [comment]
the version should be v2.0 ? Because it will have breaking changes.

And #38 should be v3.0.

https://semver.org/#spec-item-8

**Comment by DQNEO** [comment]
> Add type hints on PHP Doc function arguments/returns

If we are going to change interfaces (signatures) in #38, then these efforts will be in vain.
So I think this work is not needed in this milestone.

**Comment by DQNEO** [comment]
the rest looks good to me.
