### ISSUE TITLE
V2

### ISSUE THREAD

**Issue by HaiTo** [mercari/dietcube#38]
parent issue: https://github.com/mercari/dietcube/issues/36

# Background
Dietcube doesn't work on PHP8.0. 
DietCube cannot run on PHP8.0 due to
- Twig 1.X doesn't support PHP 8.0
- PHP Unit 5.x doesn't support PHP 8.0

Also, We want to use the modern feature since PHP version 7.X and 8.X 

# Goal
1. Runnable on PHP 8.0 
2. Be more helpful for developing.

# Milestones
- [ ] Be Runnable at PHP 8.0
- [ ] Address broken codes.
- [ ] Drop Supporting PHP
  - 7.3
- [ ] [Nice to have] Be property type declaration.

**Comment by DQNEO** [comment]
Looks good to me except for the version number. 👍
